### ISSUE TITLE
There will still have interaction when you click button the second time

### ISSUE THREAD

**Issue by CSLMeyers** [microsoft/react-native-adaptivecards#54]

**Comment by nileshprajapati007444** [comment]
@CSLMeyers 

can you please describe your issue in detail..

**Comment by CSLMeyers** [comment]
acitons on Adaptive Cards should always be clickable by default, but currently some controls didn't work when you click the second time.
@nileshprajapati007444

**Comment by nileshprajapati007444** [comment]
@CSLMeyers 

i have same issue with this package. Then I have used 'react-native-adaptivecards' package. It is working fine with all controls.

https://github.com/microsoft/react-native-adaptivecards
