### ISSUE TITLE
Out of sync with NPM published version

### ISSUE THREAD

**Issue by Kevin-Chung** [Microsoft/react-native-adaptivecards#7]
The repository's master branch has code that's ahead of what is currently published on NPM. Anyway we can get this to either be reverted, or have the version on NPM be updated to be in sync?

**Comment by DongyuZhao** [comment]
Hi Kevin:
    The 0.2.0 version on npm is the same version of the master branch. Please check it.

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: Kevin-Chung <notifications@github.com>
发送时间: 星期五, 十一月 30, 2018 9:54 下午
收件人: Microsoft/react-native-adaptivecards
抄送: Subscribed
主题: [Microsoft/react-native-adaptivecards] Out of sync with NPM published version (#7)


The repository's master branch has code that's ahead of what is currently published on NPM. Anyway we can get this to either be reverted, or have the version on NPM be updated to be in sync?

―

**Comment by DongyuZhao** [comment]
In the previous version, there were some undocumented internal required control(e.g. PeoplePicker and Counter). In the coming version of standard adaptive card, all the requirement for these undocumented controls could be fulfill by combining the new actions and elements in it. Thus we decide to remove undocumented controls and release the renderer following the standard. This is what we do for 0.2.0.

However, 0.1.0 has some accessibility issue and we need to fix it immediately and do not want to break production rely on those undocumented control, we released 0.1.1 and 0.1.2 to fix them. 

As 0.1.2 is released after 0.2.0, npm auto pick 0.1.2 as the default version now.
